dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm test
before_script:
  - testrpc > /dev/null &
  - sleep 20
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
